/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState, useMemo } from 'react';
import { Download, RefreshCw, Edit } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';

import { ToolLayout } from '@/components/tools/ToolLayout';
import { getToolById } from '@/data/tools';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export default function CoverLetterTemplate() {
  const tool = getToolById('cover-letter') || {
    id: 'cover-letter',
    name: 'Cover Letter Builder',
    description: 'Create professional cover letters with customizable templates and download them as a PDF.',
    metaTitle: 'Free Cover Letter Builder & Generator | ToolNest',
    metaDescription: 'Generate custom cover letters. Input job details, edit the body in a live preview text editor, and download as a PDF.',
    category: 'text',
  };

  // State Form fields
  const [fullName, setFullName] = useState('John Doe');
  const [email, setEmail] = useState('johndoe@example.com');
  const [phone, setPhone] = useState('(555) 019-2834');
  const [address, setAddress] = useState('New York, NY');

  const [company, setCompany] = useState('Tech Solutions Inc.');
  const [manager, setManager] = useState('Hiring Manager');
  const [jobTitle, setJobTitle] = useState('Senior Frontend Developer');

  const [skills, setSkills] = useState('React, TypeScript, Tailwind CSS, Next.js');
  const [experience, setExperience] = useState('5');
  const [highlights, setHighlights] = useState('Successfully optimized web performance by 40% and led a team of three junior developers.');

  const [templateStyle, setTemplateStyle] = useState<'classic' | 'modern'>('classic');

  // Auto-generate template text based on inputs
  const autoGeneratedBody = useMemo(() => {
    return `Dear ${manager},

I am writing to express my strong interest in the ${jobTitle} position at ${company}. With over ${experience} years of professional experience in the industry and a solid background in engineering, I am confident that I can make a significant contribution to your team.

Throughout my career, I have honed key capabilities, particularly in ${skills}. I take pride in delivering clean, maintainable code and solving complex technical challenges. In my previous role, I ${highlights}.

I am drawn to ${company} because of your commitment to technical innovation and high-quality software solutions. I would welcome the opportunity to discuss how my qualifications align with your engineering goals.

Thank you for your time and consideration.

Sincerely,

${fullName}`;
  }, [fullName, manager, jobTitle, company, experience, skills, highlights]);

  // Allow custom edits to the generated text
  const [editedBody, setEditedBody] = useState('');
  const [isEditing, setIsEditing] = useState(false);

  const activeBody = isEditing ? editedBody : autoGeneratedBody;

  const handleEditClick = () => {
    if (!isEditing) {
      setEditedBody(autoGeneratedBody);
    }
    setIsEditing(true);
  };

  const handleResetClick = () => {
    setIsEditing(false);
    setEditedBody('');
  };

  const downloadPdf = async () => {
    try {
      const pdfDoc = await PDFDocument.create();
      const page = pdfDoc.addPage([595.27, 841.89]); // A4 size in points
      const { width, height } = page.getSize();

      const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

      const margin = 50;
      let y = height - margin;

      // 1. Draw Header
      if (templateStyle === 'modern') {
        // Draw colorful banner
        page.drawRectangle({
          x: 0,
          y: height - 100,
          width: width,
          height: 100,
          color: rgb(0.1, 0.45, 0.8), // royal blue
        });
        page.drawText(fullName, {
          x: margin,
          y: height - 50,
          size: 20,
          font: fontBold,
          color: rgb(1, 1, 1),
        });
        page.drawText(`${email}  |  ${phone}  |  ${address}`, {
          x: margin,
          y: height - 75,
          size: 10,
          font: font,
          color: rgb(0.9, 0.9, 0.9),
        });
        y = height - 140;
      } else {
        // Classic header
        page.drawText(fullName, {
          x: margin,
          y: y,
          size: 20,
          font: fontBold,
          color: rgb(0.1, 0.1, 0.1),
        });
        y -= 20;
        page.drawText(`${email}  |  ${phone}  |  ${address}`, {
          x: margin,
          y: y,
          size: 10,
          font: font,
          color: rgb(0.4, 0.4, 0.4),
        });
        y -= 30;
      }

      // 2. Draw Date & Recipient Details
      const todayStr = new Date().toLocaleDateString(undefined, {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });

      page.drawText(todayStr, { x: margin, y: y, size: 10, font: font, color: rgb(0.2, 0.2, 0.2) });
      y -= 25;

      page.drawText(`To:`, { x: margin, y: y, size: 10, font: fontBold, color: rgb(0.2, 0.2, 0.2) });
      y -= 15;
      page.drawText(manager, { x: margin, y: y, size: 10, font: font, color: rgb(0.2, 0.2, 0.2) });
      y -= 15;
      page.drawText(company, { x: margin, y: y, size: 10, font: font, color: rgb(0.2, 0.2, 0.2) });
      y -= 30;

      // 3. Draw Body Paragraphs
      const paragraphs = activeBody.split('\n\n');
      const maxLineWidth = width - margin * 2;
      const fontSize = 10.5;
      const lineHeight = 16;

      for (const para of paragraphs) {
        if (y < margin + 40) {
          // Add new page if run out of space
          // Simplified: assume 1 page A4 is enough for a standard single cover letter
          break;
        }

        // Wrap words manually
        const words = para.replace(/\n/g, ' ').split(' ');
        let currentLine = '';
        const lines: string[] = [];

        for (const word of words) {
          const testLine = currentLine ? `${currentLine} ${word}` : word;
          const testWidth = font.widthOfTextAtSize(testLine, fontSize);
          if (testWidth > maxLineWidth) {
            lines.push(currentLine);
            currentLine = word;
          } else {
            currentLine = testLine;
          }
        }
        if (currentLine) {
          lines.push(currentLine);
        }

        // Draw wrapped lines
        for (const line of lines) {
          page.drawText(line, {
            x: margin,
            y: y,
            size: fontSize,
            font: font,
            color: rgb(0.15, 0.15, 0.15),
          });
          y -= lineHeight;
        }
        y -= 10; // spacing between paragraphs
      }

      const pdfBytes = await pdfDoc.save();
      const blob = new Blob([pdfBytes as BlobPart], { type: 'application/pdf' });
      const downloadUrl = URL.createObjectURL(blob);

      const link = document.createElement('a');
      link.href = downloadUrl;
      link.download = `${fullName.replace(/\s+/g, '_')}_Cover_Letter.pdf`;
      link.click();
      URL.revokeObjectURL(downloadUrl);
    } catch {
      alert('Error building PDF. Please check your text content fields.');
    }
  };

  return (
    <ToolLayout tool={tool as any} resultVisible={true}>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Input Panel */}
        <div className="lg:col-span-1 space-y-4 text-xs">
          {/* Contact Details */}
          <div className="rounded-xl border bg-card p-5 space-y-3 shadow-sm">
            <h3 className="font-semibold text-sm">1. Contact Information</h3>
            <div className="space-y-2.5">
              <div>
                <label className="font-medium text-muted-foreground">Full Name</label>
                <Input value={fullName} onChange={(e) => setFullName(e.target.value)} />
              </div>
              <div>
                <label className="font-medium text-muted-foreground">Email</label>
                <Input type="email" value={email} onChange={(e) => setEmail(e.target.value)} />
              </div>
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="font-medium text-muted-foreground">Phone</label>
                  <Input value={phone} onChange={(e) => setPhone(e.target.value)} />
                </div>
                <div>
                  <label className="font-medium text-muted-foreground">Address / City</label>
                  <Input value={address} onChange={(e) => setAddress(e.target.value)} />
                </div>
              </div>
            </div>
          </div>

          {/* Job Details */}
          <div className="rounded-xl border bg-card p-5 space-y-3 shadow-sm">
            <h3 className="font-semibold text-sm">2. Recipient & Role</h3>
            <div className="space-y-2.5">
              <div>
                <label className="font-medium text-muted-foreground">Target Company Name</label>
                <Input value={company} onChange={(e) => setCompany(e.target.value)} />
              </div>
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="font-medium text-muted-foreground">Job Title</label>
                  <Input value={jobTitle} onChange={(e) => setJobTitle(e.target.value)} />
                </div>
                <div>
                  <label className="font-medium text-muted-foreground">Hiring Manager</label>
                  <Input value={manager} onChange={(e) => setManager(e.target.value)} />
                </div>
              </div>
            </div>
          </div>

          {/* Background and Highlights */}
          <div className="rounded-xl border bg-card p-5 space-y-3 shadow-sm">
            <h3 className="font-semibold text-sm">3. Experience & Pitch</h3>
            <div className="space-y-2.5">
              <div className="grid grid-cols-3 gap-2 items-end">
                <div className="col-span-2">
                  <label className="font-medium text-muted-foreground">Key Technical Skills</label>
                  <Input value={skills} onChange={(e) => setSkills(e.target.value)} />
                </div>
                <div>
                  <label className="font-medium text-muted-foreground">Experience (Yrs)</label>
                  <Input type="number" value={experience} onChange={(e) => setExperience(e.target.value)} min="0" />
                </div>
              </div>
              <div>
                <label className="font-medium text-muted-foreground">Major Achievement / Highlight</label>
                <Textarea
                  value={highlights}
                  onChange={(e) => setHighlights(e.target.value)}
                  placeholder="Led migration of standard servers to cloud, saving 30% budget..."
                  rows={3}
                />
              </div>
            </div>
          </div>
        </div>

        {/* Live Preview Panel */}
        <div className="lg:col-span-2 space-y-4">
          <div className="flex justify-between items-center text-xs">
            <div className="flex gap-2">
              <Button
                variant={templateStyle === 'classic' ? 'default' : 'outline'}
                size="sm"
                onClick={() => setTemplateStyle('classic')}
              >
                Classic Serif
              </Button>
              <Button
                variant={templateStyle === 'modern' ? 'default' : 'outline'}
                size="sm"
                onClick={() => setTemplateStyle('modern')}
              >
                Modern Header
              </Button>
            </div>

            <div className="flex gap-2">
              {!isEditing ? (
                <Button variant="outline" size="sm" onClick={handleEditClick} className="gap-1">
                  <Edit className="w-3.5 h-3.5" /> Customize Text
                </Button>
              ) : (
                <Button variant="ghost" size="sm" onClick={handleResetClick} className="text-red-500 hover:bg-red-50">
                  <RefreshCw className="w-3.5 h-3.5 mr-1" /> Reset Auto-Text
                </Button>
              )}
              <Button size="sm" onClick={downloadPdf} className="gap-1.5 font-bold">
                <Download className="w-4 h-4" /> Download PDF
              </Button>
            </div>
          </div>

          {/* Letter preview sheet */}
          <div className="rounded-xl border bg-card p-8 shadow-sm min-h-[500px] flex flex-col justify-between font-serif relative">
            {isEditing ? (
              <Textarea
                value={editedBody}
                onChange={(e) => setEditedBody(e.target.value)}
                className="w-full h-[450px] font-mono text-xs leading-relaxed resize-none border-none focus-visible:ring-0 p-0 focus-visible:ring-offset-0"
              />
            ) : (
              <div className="space-y-4 text-xs leading-relaxed text-foreground/90 whitespace-pre-wrap">
                {/* Header mock */}
                <div className={`font-sans pb-4 border-b not-italic ${templateStyle === 'modern' ? 'bg-primary/5 p-4 rounded' : ''}`}>
                  <h4 className="text-lg font-bold text-foreground">{fullName}</h4>
                  <p className="text-muted-foreground">{email}  |  {phone}  |  {address}</p>
                </div>

                <div className="text-[10px] text-muted-foreground font-sans">
                  {new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}
                </div>

                <div className="font-sans text-[10px]">
                  <p className="font-bold text-foreground">To:</p>
                  <p>{manager}</p>
                  <p>{company}</p>
                </div>

                <p>{activeBody.split('\n\n').slice(0, -1).join('\n\n')}</p>
              </div>
            )}
            {!isEditing && (
              <p className="text-xs font-serif leading-relaxed text-foreground/90 mt-4 whitespace-pre-wrap">
                Sincerely,
                {"\n"}
                {fullName}
              </p>
            )}
          </div>
        </div>
      </div>
    </ToolLayout>
  );
}
