import os

base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tools_path = os.path.join(base, 'src', 'data', 'tools.ts')

with open(tools_path, 'r', encoding='utf-8') as f:
    content = f.read()

if "id: 'create-zip'" in content:
    print("Already patched")
    exit(0)

new_tools = """
  {
    id: 'create-zip',
    name: 'Create ZIP',
    description: 'Combine multiple files into a single ZIP archive with one click.',
    category: 'archive',
    path: '/tools/create-zip',
    icon: 'FileArchive',
    keywords: ['zip', 'create', 'compress', 'archive', 'folder'],
    metaTitle: 'Create ZIP Archive Online Free - Compress Files | ToolNest',
    metaDescription: 'Create ZIP archives from multiple files in your browser. Fast, free, and private.',
  },
  {
    id: 'extract-archive',
    name: 'Extract Archive',
    description: 'Extract ZIP archives and download individual files. Only ZIP is supported client-side.',
    category: 'archive',
    path: '/tools/extract-archive',
    icon: 'FolderOpen',
    keywords: ['extract', 'unzip', 'rar', '7z', 'tar', 'gz', 'archive'],
    metaTitle: 'Extract ZIP Archive Online Free | ToolNest',
    metaDescription: 'Extract ZIP archives in your browser. Download individual files or all at once.',
  },
  {
    id: 'compress-folder',
    name: 'Compress Folder to ZIP',
    description: 'Select an entire folder and compress it into a ZIP archive.',
    category: 'archive',
    path: '/tools/compress-folder',
    icon: 'FolderInput',
    keywords: ['zip', 'folder', 'compress', 'directory'],
    metaTitle: 'Compress Folder to ZIP Online Free | ToolNest',
    metaDescription: 'Compress entire folders to ZIP archives directly in your browser. Free tool.',
  },
  {
    id: 'unzip-specific',
    name: 'Unzip Specific Files',
    description: 'Open a ZIP and selectively download only the files you need.',
    category: 'archive',
    path: '/tools/unzip-specific',
    icon: 'Files',
    keywords: ['zip', 'extract', 'selective', 'partial'],
    metaTitle: 'Extract Specific Files from ZIP Online Free | ToolNest',
    metaDescription: 'Open ZIP archives and download only selected files. Client-side processing.',
  },
  {
    id: 'whats-my-ip',
    name: "What's My IP?",
    description: 'Find your public IP address, approximate location, and ISP details.',
    category: 'network',
    path: '/tools/whats-my-ip',
    icon: 'Globe',
    keywords: ['ip', 'address', 'location', 'isp', 'country'],
    metaTitle: "What's My IP Address? - Find Public IP & Location | ToolNest",
    metaDescription: 'Find your public IP address, country, city, and ISP details instantly.',
  },
  {
    id: 'user-agent-parser',
    name: 'User-Agent Parser',
    description: 'Parse your browser user-agent string to reveal OS, browser, and device info.',
    category: 'network',
    path: '/tools/user-agent-parser',
    icon: 'Monitor',
    keywords: ['user', 'agent', 'browser', 'os', 'device'],
    metaTitle: 'User-Agent Parser Online Free - Browser & OS Detector | ToolNest',
    metaDescription: 'Parse user-agent strings to detect browser, operating system, and device.',
  },
  {
    id: 'internet-speed-test',
    name: 'Internet Speed Test',
    description: 'Measure your download speed by downloading a test file.',
    category: 'network',
    path: '/tools/internet-speed-test',
    icon: 'Gauge',
    keywords: ['speed', 'test', 'bandwidth', 'mbps', 'download'],
    metaTitle: 'Internet Speed Test Online Free - Check Download Speed | ToolNest',
    metaDescription: 'Test your internet download speed with a quick browser-based benchmark.',
  },
  {
    id: 'url-parser',
    name: 'URL Parser',
    description: 'Break down any URL into protocol, host, port, path, query, and hash.',
    category: 'network',
    path: '/tools/url-parser',
    icon: 'Link',
    keywords: ['url', 'query', 'parameters', 'parse'],
    metaTitle: 'URL Parser Online Free - Query & Parameter Breakdown | ToolNest',
    metaDescription: 'Parse URLs to extract protocol, host, path, query parameters, and more.',
  },
  {
    id: 'meta-tags-preview',
    name: 'Meta Tags / Open Graph Preview',
    description: 'Preview how your page will look when shared on Facebook, Twitter, and LinkedIn.',
    category: 'social',
    path: '/tools/meta-tags-preview',
    icon: 'Tags',
    keywords: ['meta', 'tags', 'open', 'graph', 'facebook', 'twitter'],
    metaTitle: 'Meta Tags & Open Graph Preview Tool Online Free | ToolNest',
    metaDescription: 'Preview your meta tags and Open Graph cards for Facebook, Twitter, and LinkedIn.',
  },
  {
    id: 'youtube-thumbnail',
    name: 'YouTube Thumbnail Downloader',
    description: 'Paste a YouTube URL and download thumbnails in various qualities.',
    category: 'social',
    path: '/tools/youtube-thumbnail',
    icon: 'Youtube',
    keywords: ['youtube', 'thumbnail', 'download', 'video'],
    metaTitle: 'YouTube Thumbnail Downloader Online Free | ToolNest',
    metaDescription: 'Download YouTube video thumbnails in HD, SD, and default qualities for free.',
  },
  {
    id: 'hashtag-generator',
    name: 'Hashtag Generator',
    description: 'Generate relevant hashtags from keywords for social media posts.',
    category: 'social',
    path: '/tools/hashtag-generator',
    icon: 'Hash',
    keywords: ['hashtag', 'social', 'media', 'marketing'],
    metaTitle: 'Hashtag Generator Online Free - Social Media Tags | ToolNest',
    metaDescription: 'Generate social media hashtags from keywords. Boost your post visibility.',
  },
  {
    id: 'email-signature',
    name: 'Email Signature Generator',
    description: 'Create professional HTML email signatures with your contact details.',
    category: 'social',
    path: '/tools/email-signature',
    icon: 'Mail',
    keywords: ['email', 'signature', 'html', 'generator'],
    metaTitle: 'Email Signature Generator Online Free - HTML | ToolNest',
    metaDescription: 'Create professional HTML email signatures with contact info and branding.',
  },
  {
    id: 'qr-code-scanner',
    name: 'QR Code Scanner',
    description: 'Scan QR codes from your camera or uploaded images.',
    category: 'social',
    path: '/tools/qr-code-scanner',
    icon: 'ScanLine',
    keywords: ['qr', 'code', 'scanner', 'webcam', 'image'],
    metaTitle: 'QR Code Scanner Online Free - Camera & Image | ToolNest',
    metaDescription: 'Scan QR codes using your webcam or by uploading an image. Free online tool.',
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator / Scanner',
    description: 'Generate Code128/EAN barcodes and scan from images.',
    category: 'social',
    path: '/tools/barcode-generator',
    icon: 'Barcode',
    keywords: ['barcode', 'generator', 'scanner', 'code128', 'ean'],
    metaTitle: 'Barcode Generator & Scanner Online Free - Code128 / EAN | ToolNest',
    metaDescription: 'Generate Code128 and EAN barcodes or scan barcodes from images. Free tool.',
  },
  {
    id: 'meme-generator',
    name: 'Meme Generator',
    description: 'Upload an image and add top/bottom text to create memes.',
    category: 'design',
    path: '/tools/meme-generator',
    icon: 'Laugh',
    keywords: ['meme', 'generator', 'image', 'text', 'overlay'],
    metaTitle: 'Meme Generator Online Free - Add Text to Images | ToolNest',
    metaDescription: 'Create memes by uploading images and adding top and bottom text. Download as PNG.',
  },
  {
    id: 'image-collage',
    name: 'Image Collage Maker',
    description: 'Combine multiple images into a collage with configurable grid layouts.',
    category: 'design',
    path: '/tools/image-collage',
    icon: 'Grid3x3',
    keywords: ['collage', 'image', 'grid', 'layout'],
    metaTitle: 'Image Collage Maker Online Free - Grid Layouts | ToolNest',
    metaDescription: 'Create image collages with customizable grid layouts. Combine photos in your browser.',
  },
  {
    id: 'image-splitter',
    name: 'Image Splitter',
    description: 'Split an image into a grid of tiles for Instagram or other uses.',
    category: 'design',
    path: '/tools/image-splitter',
    icon: 'Split',
    keywords: ['image', 'split', 'grid', 'instagram', 'tiles'],
    metaTitle: 'Image Splitter Online Free - Grid & Tiles | ToolNest',
    metaDescription: 'Split images into grids and tiles. Perfect for Instagram carousel posts.',
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Generate favicon PNGs at multiple sizes from a square image.',
    category: 'design',
    path: '/tools/favicon-generator',
    icon: 'Square',
    keywords: ['favicon', 'ico', 'icon', 'website'],
    metaTitle: 'Favicon Generator Online Free - Multi-Size PNGs | ToolNest',
    metaDescription: 'Generate favicon images at 16x16 to 256x256 from a square image. Free tool.',
  },
  {
    id: 'whiteboard',
    name: 'Drawing / Whiteboard',
    description: 'Freehand draw on a canvas with colors, brush sizes, eraser, and undo.',
    category: 'design',
    path: '/tools/whiteboard',
    icon: 'Pencil',
    keywords: ['draw', 'whiteboard', 'sketch', 'canvas'],
    metaTitle: 'Online Whiteboard & Drawing Tool Free | ToolNest',
    metaDescription: 'Draw and sketch on an online whiteboard with multiple tools. Download as PNG.',
  },
  {
    id: 'palette-from-image',
    name: 'Color Palette from Image',
    description: 'Extract dominant color palettes from any uploaded image.',
    category: 'design',
    path: '/tools/palette-from-image',
    icon: 'Palette',
    keywords: ['color', 'palette', 'image', 'extract', 'dominant'],
    metaTitle: 'Color Palette from Image Online Free | ToolNest',
    metaDescription: 'Extract dominant colors from any image and copy hex codes. Free tool.',
  },
  {
    id: 'ocr-image',
    name: 'OCR Image to Text',
    description: 'Extract text from images using Tesseract OCR.',
    category: 'productivity',
    path: '/tools/ocr-image',
    icon: 'Scan',
    keywords: ['ocr', 'text', 'recognition', 'image', 'extract'],
    metaTitle: 'OCR Image to Text Online Free - Tesseract | ToolNest',
    metaDescription: 'Extract text from images and scanned documents using Tesseract OCR. Private & free.',
  },
  {
    id: 'handwriting-generator',
    name: 'Handwriting Text Generator',
    description: 'Generate handwritten-style text on lined paper background.',
    category: 'productivity',
    path: '/tools/handwriting-generator',
    icon: 'Pen',
    keywords: ['handwriting', 'font', 'text', 'generator'],
    metaTitle: 'Handwriting Text Generator Online Free | ToolNest',
    metaDescription: 'Convert typed text into handwriting-style images. Save as PNG.',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel / CSV',
    description: 'Extract tables and text from PDFs and convert to CSV format.',
    category: 'productivity',
    path: '/tools/pdf-to-excel',
    icon: 'FileSpreadsheet',
    keywords: ['pdf', 'csv', 'excel', 'convert', 'tables'],
    metaTitle: 'PDF to Excel / CSV Converter Online Free | ToolNest',
    metaDescription: 'Convert PDF tables and text to CSV format directly in your browser. Free.',
  },
  {
    id: 'merge-word',
    name: 'Merge Word Documents',
    description: 'Combine text content from multiple .docx files into one document.',
    category: 'productivity',
    path: '/tools/merge-word',
    icon: 'FileMerge',
    keywords: ['word', 'merge', 'docx', 'combine'],
    metaTitle: 'Merge Word Documents Online Free - DOCX | ToolNest',
    metaDescription: 'Merge multiple Word documents into one. Simple text-only merge in browser.',
  },
  {
    id: 'split-word',
    name: 'Split Word Document',
    description: 'Split a Word document into multiple files at specified points.',
    category: 'productivity',
    path: '/tools/split-word',
    icon: 'FileSplit',
    keywords: ['word', 'split', 'docx', 'separate'],
    metaTitle: 'Split Word Document Online Free - DOCX | ToolNest',
    metaDescription: 'Split Word documents into multiple files. Simple text extraction and splitting.',
  },
  {
    id: 'word-cloud',
    name: 'Word Cloud Generator',
    description: 'Create a visual word cloud from any text with customizable colors.',
    category: 'fun',
    path: '/tools/word-cloud',
    icon: 'Cloud',
    keywords: ['word', 'cloud', 'frequency', 'text', 'visual'],
    metaTitle: 'Word Cloud Generator Online Free - Text Visualization | ToolNest',
    metaDescription: 'Generate beautiful word clouds from any text. Customize colors and download as PNG.',
  },
  {
    id: 'readability-score',
    name: 'Readability Score',
    description: 'Calculate Flesch Reading Ease and grade level for any text.',
    category: 'fun',
    path: '/tools/readability-score',
    icon: 'BookOpen',
    keywords: ['readability', 'flesch', 'kincaid', 'grade', 'level'],
    metaTitle: 'Readability Score Calculator Online Free | ToolNest',
    metaDescription: 'Calculate Flesch Reading Ease and grade level for your text. Free online tool.',
  },
  {
    id: 'char-frequency',
    name: 'Character Frequency Counter',
    description: 'Count the frequency of each character or letter in your text.',
    category: 'fun',
    path: '/tools/char-frequency',
    icon: 'BarChart3',
    keywords: ['character', 'frequency', 'chart', 'letter'],
    metaTitle: 'Character Frequency Counter Online Free - Text Stats | ToolNest',
    metaDescription: 'Count the frequency of each character in your text and visualize as a bar chart.',
  },
  {
    id: 'spin-wheel',
    name: 'Spin the Wheel',
    description: 'Spin a customizable wheel to randomly pick a winner.',
    category: 'fun',
    path: '/tools/spin-wheel',
    icon: 'RotateCw',
    keywords: ['spin', 'wheel', 'random', 'picker', 'chance'],
    metaTitle: 'Spin the Wheel Online Free - Random Picker | ToolNest',
    metaDescription: 'Spin a customizable wheel to randomly pick a winner. Fun and free online tool.',
  },
  {
    id: 'random-name-picker',
    name: 'Random Name Picker',
    description: 'Enter names and randomly pick winners.',
    category: 'fun',
    path: '/tools/random-name-picker',
    icon: 'Users',
    keywords: ['random', 'name', 'picker', 'draw', 'winner'],
    metaTitle: 'Random Name Picker Online Free - Draw Winner | ToolNest',
    metaDescription: 'Enter names and randomly pick winners. Great for giveaways and raffles.',
  },
  {
    id: 'screen-recorder',
    name: 'Screen Recorder',
    description: 'Record your screen directly in your browser. Download as WebM.',
    category: 'video',
    path: '/tools/screen-recorder',
    icon: 'Monitor',
    keywords: ['screen', 'record', 'capture', 'desktop'],
    metaTitle: 'Screen Recorder Online Free - Browser Capture | ToolNest',
    metaDescription: 'Record your screen directly in your browser. Download as WebM. No installation.',
  },
  {
    id: 'webcam-recorder',
    name: 'Webcam Recorder / Photo Booth',
    description: 'Record from your webcam or take photos. Download images and videos.',
    category: 'video',
    path: '/tools/webcam-recorder',
    icon: 'Camera',
    keywords: ['webcam', 'record', 'photo', 'booth', 'camera'],
    metaTitle: 'Webcam Recorder & Photo Booth Online Free | ToolNest',
    metaDescription: 'Record from your webcam or take photos. Download images and videos. Free tool.',
  },
  {
    id: 'karaoke-recorder',
    name: 'Karaoke Recorder',
    description: 'Sing along to instrumental tracks and record your performance.',
    category: 'audio',
    path: '/tools/karaoke-recorder',
    icon: 'Mic2',
    keywords: ['karaoke', 'record', 'sing', 'audio', 'mix'],
    metaTitle: 'Karaoke Recorder Online Free - Sing & Record | ToolNest',
    metaDescription: 'Sing along to instrumental tracks and record your performance. Free browser tool.',
  },
"""

idx = content.rfind('];', 0, content.index('export const popularTools'))
new_content = content[:idx] + new_tools + content[idx:]

with open(tools_path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print("Patched src/data/tools.ts")
